spring.application.name=ai-task-manager

spring.datasource.url=jdbc:postgresql://localhost:5433/task_manager
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080