spring.application.name=ai-task-manager
gemini.api.key=${GEMINI_API_KEY:dummy_key}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/task_manager}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080